### ISSUE TITLE
Related Products: Fatal error when used outside of a single product template

### ISSUE THREAD

**Issue by maxlaf** [woocommerce/woocommerce-gutenberg-products-block#10959]
## Describe the bug

When adding the Related Products block to somewhere other than the single product template a fatal error is thrown either on the frontend or when saving a page.

## To reproduce

1. Install an FSE theme.
2. Add the Related Products block to the cart/checkout template.
3. Add a product to your cart.
4. Navigate to the cart/checkout
5. See fatal error.

2a. Add the related products block to a sample page which isn't a product.
3. Save the page.
4. See `Saving failed` error and a fatal error in the logs under WooCommerce > Status > Logs

```
2023-09-14T20:43:58+00:00 CRITICAL Uncaught Error: Call to a member function get_id() on bool in /srv/users/user7e036348/apps/user7e036348/public/wp-content/plugins/woo-gutenberg-products-block/src/BlockTypes/RelatedProducts.php:161
Stack trace:
#0 /srv/users/user7e036348/apps/user7e036348/public/wp-content/plugins/woo-gutenberg-products-block/src/BlockTypes/RelatedProducts.php(99): Automattic\WooCommerce\Blocks\BlockTypes\RelatedProducts->get_related_products_ids(5)
#1 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/class-wp-hook.php(312): Automattic\WooCommerce\Blocks\BlockTypes\RelatedProducts->build_query(Array)
#2 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#3 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/blocks.php(1464): apply_filters('query_loop_bloc...', Array, Object(WP_Block), 1)
#4 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/blocks/post-template.php(55): build_query_vars_from_query_block(Object(WP_Block), 1)
#5 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/class-wp-block.php(258): render_block_core_post_template(Array, '', Object(WP_Block))
#6 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/class-wp-block.php(244): WP_Block->render()
#7 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/class-wp-block.php(244): WP_Block->render()
#8 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/class-wp-block.php(244): WP_Block->render()
#9 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/blocks.php(1133): WP_Block->render()
#10 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/blocks.php(1171): render_block(Array)
#11 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/class-wp-hook.php(310): do_blocks('<!-- wp:paragra...')
#12 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/plugin.php(205): WP_Hook->apply_filters('<!-- wp:paragra...', Array)
#13 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1864): apply_filters('the_content', '<!-- wp:paragra...')
#14 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(952): WP_REST_Posts_Controller->prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request))
#15 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/rest-api/class-wp-rest-server.php(1188): WP_REST_Posts_Controller->update_item(Object(WP_REST_Request))
#16 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/rest-api/class-wp-rest-server.php(1035): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wp/v2/pages/(?...', Array, NULL)
#17 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/rest-api/class-wp-rest-server.php(447): WP_REST_Server->dispatch(Object(WP_REST_Request))
#18 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/rest-api.php(418): WP_REST_Server->serve_request('/wp/v2/pages/2')
#19 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/class-wp-hook.php(310): rest_api_loaded(Object(WP))
#20 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#21 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#22 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/class-wp.php(398): do_action_ref_array('parse_request', Array)
#23 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/class-wp.php(779): WP->parse_request('')
#24 /srv/users/user7e036348/apps/user7e036348/public/wp-includes/functions.php(1335): WP->main('')
#25 /srv/users/user7e036348/apps/user7e036348/public/wp-blog-header.php(16): wp()
#26 /srv/users/user7e036348/apps/user7e036348/public/index.php(17): require('/srv/users/user...')
#27 {main}
  thrown in /srv/users/user7e036348/apps/user7e036348/public/wp-content/plugins/woo-gutenberg-products-block/src/BlockTypes/RelatedProducts.php on line 161
```

## Expected behavior

No fatal errors. 

If the Related Products block cannot be used on a particular page or template, I'd expect a notice or to be prevented from adding it.

## Screenshots

![ogwwGF.png](https://github.com/woocommerce/woocommerce-blocks/assets/56649567/6a36d52f-a07b-4e6e-a575-070bdc1acde7)
![NIOZku.png](https://github.com/woocommerce/woocommerce-blocks/assets/56649567/594b303c-88b9-4a0f-93e6-d2e3ce4997ed)

### WordPress (please complete the following information):

-   WordPress version: 6.3.1
-   Gutenberg version (if installed): N/A
-   WooCommerce version: 8.1.0
-   WooCommerce Blocks version: 11.1.0

System status report:

<details>

```
### WordPress Environment ###

WordPress address (URL): https://poor-cuckoo.jurassic.ninja
Site address (URL): https://poor-cuckoo.jurassic.ninja
WC Version: 8.1.0
REST API Version: ✔ 8.1.0
WC Blocks Version: ✔ 11.1.0
Action Scheduler Version: ✔ 3.6.2
Log Directory Writable: ✔
WP Version: 6.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.57 (Unix) OpenSSL/1.0.2g
PHP Version: 8.0.30
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.1.0
WC Database Prefix: wp_
Total Database Size: 5.41MB
Database Data Size: 3.68MB
Database Index Size: 1.73MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 8
post: 2
product: 18
product_variation: 7
revision: 5
wp_global_styles: 1
wp_navigation: 1
wp_template: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Companion Plugin: by Osk – 1.30
Jetpack: by Automattic – 12.5
WooCommerce Blocks: by Automattic – 11.1.0
WooCommerce: by Automattic – 8.1.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Three
Version: 1.2
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /srv/users/user7e036348/apps/user7e036348/public/wp-content/plugins/woo-gutenberg-products-block/templates/notices/error.php
/srv/users/user7e036348/apps/user7e036348/public/wp-content/plugins/woo-gutenberg-products-block/templates/notices/notice.php
/srv/users/user7e036348/apps/user7e036348/public/wp-content/plugins/woo-gutenberg-products-block/templates/notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-09-15 00:56:39 +00:00
Options: ✔
Notes: 60
Onboarding: skipped

### Action Scheduler ###

Complete: 31
Oldest: 2023-09-14 00:56:53 +0000
Newest: 2023-09-14 20:31:44 +0000

Failed: 1
Oldest: 2023-09-14 20:31:44 +0000
Newest: 2023-09-14 20:31:44 +0000

Pending: 1
Oldest: 2023-09-15 00:56:53 +0000
Newest: 2023-09-15 00:56:53 +0000


### Status report information ###

Generated at: 2023-09-14 20:50:36 +00:00
```

</details>

**Comment by kmanijak** [comment]
Hi @maxlaf, thanks a lot for raising this issue 🙌 

Related Product is not supposed to be used outside of Single Product template or Single Product block and there was an issue that allowed it to be used elsewhere. 

In https://github.com/woocommerce/woocommerce-blocks/pull/10978 we provided the fix that will hide it in other places. Until the fix that hides Related Products from the inserter is released, please avoid adding Related Products in other places than the Single Product block and template as it was unexpectedly available there 🙏 .

Thanks a lot!

**Comment by maxlaf** [comment]
Thanks for the context @kmanijak! I missed that PR and didn't see another issue for this, so I was unsure if it was a known issue or not.

Much appreciated 🙏

**Comment by kmanijak** [comment]
> I missed that PR and didn't see another issue for this, so I was unsure if it was a known issue or not.

PR was created as a result of this issue, so thank _you_!
