### ISSUE TITLE
Fatal error with checkout block in editor

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce-gutenberg-products-block#2071]
## to reproduce
- Edit a page with checkout block. Or add checkout block to a page, save and reload.
- Fatal error!

Looks like the new cart apis (https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/2044) are accessing a nonexistent `WC()->session`.

```
2020-03-30T21:17:35+00:00 CRITICAL Uncaught Error: Call to a member function get() on null in /var/www/html/wp-content/plugins/woocommerce-gutenberg-products-block/src/RestApi/StoreApi/Routes/Checkout.php:187
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce-gutenberg-products-block/src/RestApi/StoreApi/Routes/Checkout.php(233): Automattic\WooCommerce\Blocks\RestApi\StoreApi\Routes\Checkout->get_draft_order_id()
#1 /var/www/html/wp-content/plugins/woocommerce-gutenberg-products-block/src/RestApi/StoreApi/Routes/Checkout.php(95): Automattic\WooCommerce\Blocks\RestApi\StoreApi\Routes\Checkout->create_or_update_draft_order()
#2 /var/www/html/wp-content/plugins/woocommerce-gutenberg-products-block/src/RestApi/StoreApi/Routes/AbstractRoute.php(68): Automattic\WooCommerce\Blocks\RestApi\StoreApi\Routes\Checkout->get_route_response()
#3 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(946): Automattic\WooCommerce\Blocks\RestApi\StoreApi\Routes\AbstractRoute->get_response()
#4 /var/www/html/wp-includes/rest-api.php(429): WP_REST_ in /var/www/html/wp-content/plugins/woocommerce-gutenberg-products-block/src/RestApi/StoreApi/Routes/Checkout.php on line 187
```

**Comment by haszari** [comment]
Also seeing a JS error breaking cart & checkout blocks in editor :)

<img width="501" alt="Screen Shot 2020-03-31 at 11 33 10 AM" src="https://user-images.githubusercontent.com/4167300/77968302-7fa8e680-7343-11ea-9515-0dfd4635c0c0.png">
