### ISSUE TITLE
Changing the session handler causes fatal error

### ISSUE THREAD

**Issue by seb86** [woocommerce/woocommerce-gutenberg-products-block#2488]
I changed my session handler and only in the WordPress dashboard or during a REST API request does it give the following error.

Any reason why?

```
[14-May-2020 13:04:12 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in W:\xampp\htdocs\cocart\wordpress\wp-content\plugins\woocommerce\includes\class-wc-cart-session.php:73
Stack trace:
#0 W:\xampp\htdocs\cocart\wordpress\wp-content\plugins\woocommerce\includes\class-wc-cart.php(610): WC_Cart_Session->get_cart_from_session()
#1 W:\xampp\htdocs\cocart\wordpress\wp-content\plugins\woocommerce\packages\woocommerce-blocks\src\RestApi.php(76): WC_Cart->get_cart()
#2 W:\xampp\htdocs\cocart\wordpress\wp-includes\class-wp-hook.php(287): Automattic\WooCommerce\Blocks\RestApi::maybe_init_cart_session(NULL)
#3 W:\xampp\htdocs\cocart\wordpress\wp-includes\plugin.php(206): WP_Hook->apply_filters(NULL, Array)
#4 W:\xampp\htdocs\cocart\wordpress\wp-includes\rest-api\class-wp-rest-server.php(143): apply_filters('rest_authentica...', NULL)
#5 W:\xampp\htdocs\cocart\wordpress\wp-includes\rest-api\class-wp-rest-server.php(339): WP_REST_Server->check_authentication()
#6 W:\xampp\htdocs\cocart\wordpress\wp-includes\rest-api.php(306): WP_REST_Server->serve_request('/wc-analytics/o...')
#7 W:\xampp\htdocs\cocart\wordpress\wp-includes\class-wp-hook.php(287): rest_api_loaded(Object(WP))
#8 W:\xampp\htdocs\cocart\wordpress\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#9 W:\xampp\htdocs\cocart\wordpress\wp-includes\plugin.php(544): WP_Hook->do_action(Array)
#10 W:\xampp\htdocs\cocart\wordpress\wp-includes\class-wp.php(388): do_action_ref_array('parse_request', Array)
#11 W:\xampp\htdocs\cocart\wordpress\wp-includes\class-wp.php(741): WP->parse_request('')
#12 W:\xampp\htdocs\cocart\wordpress\wp-includes\functions.php(1275): WP->main('')
#13 W:\xampp\htdocs\cocart\wordpress\wp-blog-header.php(16): wp()
#14 W:\xampp\htdocs\cocart\wordpress\index.php(17): require('W:\\xampp\\htdocs...')
#15 {main}
  thrown in W:\xampp\htdocs\cocart\wordpress\wp-content\plugins\woocommerce\includes\class-wc-cart-session.php on line 73
```

**Comment by seb86** [comment]
Solved!

**Comment by magemanish** [comment]
Hi @seb86 ,
Can you explain how to resolve.

i am facing same issue.
i am ussing APIs.
