### ISSUE TITLE
Running into this error in the fatal error logs for the site

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce-gutenberg-products-block#3002]
```
2020-08-12T13:56:16+00:00 CRITICAL Uncaught Error: Call to a member function get_applied_coupons() on null in /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Utilities/CartController.php:452
Stack trace:
#0 /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Routes/CartCoupons.php(64): Automattic\WooCommerce\Blocks\StoreApi\Utilities\CartController->get_cart_coupons()
woocommerce/woocommerce#1 /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Routes/AbstractRoute.php(77): Automattic\WooCommerce\Blocks\StoreApi\Routes\CartCoupons->get_route_response(Object(WP_REST_Request))
woocommerce/woocommerce#2 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/rest-api/class-wp-rest-server.php(1050): Automattic\WooCommerce\Blocks\StoreApi\Routes\AbstractRoute->get_response(Object(WP_REST_Request))
woocommerce/woocommerce#3 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/rest-api/class-wp-rest-server.php(376): WP_REST_Server-> in /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Utilities/CartController.php on line 452

2020-08-12T13:56:20+00:00 CRITICAL Uncaught Error: Call to a member function get_cart() on null in /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Utilities/CartController.php:410
Stack trace:
#0 /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Routes/CartItems.php(64): Automattic\WooCommerce\Blocks\StoreApi\Utilities\CartController->get_cart_items()
woocommerce/woocommerce#1 /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Routes/AbstractRoute.php(77): Automattic\WooCommerce\Blocks\StoreApi\Routes\CartItems->get_route_response(Object(WP_REST_Request))
woocommerce/woocommerce#2 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/rest-api/class-wp-rest-server.php(1050): Automattic\WooCommerce\Blocks\StoreApi\Routes\AbstractRoute->get_response(Object(WP_REST_Request))
woocommerce/woocommerce#3 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/rest-api/class-wp-rest-server.php(376): WP_REST_Server->dispatch(Object(W in /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Utilities/CartController.php on line 410

2020-08-12T16:13:29+00:00 CRITICAL Uncaught Error: Call to undefined function register_block_type_from_metadata() in /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/blocks/index.php:62
Stack trace:
#0 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/class-wp-hook.php(287): register_core_block_types_from_metadata('')
woocommerce/woocommerce#1 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
woocommerce/woocommerce#2 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
woocommerce/woocommerce#3 /chroot/home/ae32bbea/iheartdogs.com/html/wp-settings.php(546): do_action('init')
woocommerce/woocommerce#4 /chroot/home/ae32bbea/iheartdogs.com/html/wp-config.php(88): require_once('/chroot/home/ae...')
woocommerce/woocommerce#5 /chroot/home/ae32bbea/iheartdogs.com/html/wp-load.php(37): require_once('/chroot/home/ae...')
woocommerce/woocommerce#6 /chroot/home/ae32bbea/iheartdogs.com/html/wp-blog-header.php(13): require_once('/chroot/home/ae...')
woocommerce/woocommerce#7 /chroot/home/ae32bbea/iheartdogs.com/html/index.php(17): require('/chroot/home/ae...')
woocommerce/woocommerce#8 {main}
  thrown in /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/blocks/index.php on line 62
```

**Comment by lukecav** [comment]
Thanks for moving the issue over.

**Comment by nerrad** [comment]
Hi @lukecav 

These errors are coming from the REST endpoints (specifically the internal `wc/store/cart` route). From the behaviour it appears something is trying to crawl the rest endpoints directly without a cart session. We certainly can add some defensive checks to prevent the fatal errors from polluting the logs but I just wanted to make sure you're aware that the errors should not be indicative of issues affecting legit shoppers.
