### ISSUE TITLE
npm install throws error with eslint-plugin-woocommerce\npm-shrinkwrap.json

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-gutenberg-products-block#3071]
## Describe the bug
Unable to finish running build scripts

## To reproduce

1. Git clone the repo
2. Go to folder and run `npm install`
3. Fail to finish install

## Screenshots
```

$ npm install
npm ERR! code UNKNOWN
npm ERR! syscall open
npm ERR! path C:\Users\helga\Local Sites\sandbox\app\public\wp-content\plugins\woocommerce-blocks\node_modules\eslint-plugin-woocommerce\npm-shrinkwrap.json
npm ERR! errno -4094
npm ERR! UNKNOWN: unknown error, open 'C:\Users\helga\Local Sites\sandbox\app\public\wp-content\plugins\woocommerce-blocks\node_modules\eslint-plugin-woocommerce\npm-shrinkwrap.json'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\helga\AppData\Roaming\npm-cache\_logs\2020-08-28T18_21_24_884Z-debug.log

--
```

full log: https://pastebin.com/CREi6CJS

### Desktop (please complete the following information):
* OS: Windows 10
* Browser: Firefox

**Comment by nerrad** [comment]
Hi Kathy, what version of `npm` and `node` is installed in your system?

**Comment by helgatheviking** [comment]
Using the Linux subsystem for Windows Terminal.... which previously had been solving a lot of my issues with build scripts not being too friendly with Windows. 

Just updated node and npm to the latest...
npm = 6.14.8
node = v14.9.0

And getting further along wen running `npm install`... now hitting a new error message. Build tools always kicking my butt.


```
> nodegit@0.26.5 install /mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.26.5-node-v83-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.26.5 and node@14.9.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
/bin/sh: 1: krb5-config: not found
gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp
ERR! configure error
gyp ERR! stack
Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/nodegit/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/nodegit
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/nodegit/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp
ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
node-pre-gyp ERR! command "/usr/bin/node" "/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/nodegit
node-pre-gyp ERR! node -v v14.9.0
Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/mnt/c/Users/helga/Local Sites/sandbox/app/public/wp-content/plugins/woocommerce-blocks/node_modules/nodegit/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm WARN @emotion/native@10.0.27 requires a peer of react-native@>=0.14.0 <1 but none is installed. You must install peer dependencies yourself.
npm WARN @emotion/primitives-core@10.0.27 requires a peer of @emotion/core@^10.0.27 but none is installed. You must install peer dependencies yourself.
npm WARN @emotion/styled-base@10.0.31 requires a peer of @emotion/core@^10.0.28 but none is installed. You must install peer dependencies yourself.
npm WARN emotion-theming@10.0.27 requires a peer of @emotion/core@^10.0.27 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-url-polyfill@1.2.0 requires a peer of react-native@* but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@2.2.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended-scss@3.3.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-wordpress@13.1.0 requires a peer of stylelint@^9.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@storybook/addon-docs/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/react-dev-utils/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.26.5 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.26.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/helga/.npm/_logs/2020-09-01T01_20_12_819Z-debug.log

```

**Comment by nerrad** [comment]
HI Kathy,

In this case, node 14 is the bleeding version of Node instead of the latest release of an LTS version. It looks like the errors are from a package that doesn't support Node 14 yet. In our repo we currently build to the latest LTS version of Node which is the version 12 branch. Switching to that version of node might help you here.

**Comment by nerrad** [comment]
Another thing you'll want to do when switching versions is delete the `node_modules` folder to ensure you're building packages to the specific installed version (which is important for things like `node-gyp`)

**Comment by helgatheviking** [comment]
Reverting to node 12 seems to have done it! build script completing successfully! thanks for pointing that out.
