### ISSUE TITLE
Mini Cart: Style doesn't apply to quantity input

### ISSUE THREAD

**Issue by dinhtungdu** [woocommerce/woocommerce-gutenberg-products-block#6029]
## To reproduce

1. Edit Mini Cart Template part.
2. Set the text, link, and background color for the Mini Cart Contents block.
3. See the color doesn't apply to the quantity input in the editor.
4. Save. See the issue on the front end.

## Expected behavior

Quantity input should be styled as other elements.

## Screenshots

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/5423135/157570612-5b1dd520-f0dd-4054-86b6-2439182a7a07.png">

## Additional context

Thank @nerrad to report this issue!

**Comment by prashantpaidi** [comment]
Can I work on this issue?

**Comment by dinhtungdu** [comment]
> Can I work on this issue?

@prashantpaidi Sure, go ahead : )

**Comment by dinhtungdu** [comment]
@prashantpaidi Did you have a chance to work on this issue? Is there anything we can help with?

**Comment by prashantpaidi** [comment]
I am getting error while building the project

```
ERROR in ./assets/css/abstracts/_mixins.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: This file is already being loaded.
```

**Comment by dinhtungdu** [comment]
@prashantpaidi Did you follow instructions [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/contributors/getting-started.md)? What is your node version? If it's not v16, can you please change node to v16, remove the `node_modules`, then try again?

**Comment by prashantpaidi** [comment]
Yes, I have tried all the instructions and even tried multiple times deleting the `node_module`.

**Comment by dinhtungdu** [comment]
@prashantpaidi can you provide more information about your development environment? For example the OS version, node version, and shell version. Also, can you confirm you're using the latest `trunk` commit?

**Comment by prashantpaidi** [comment]
I am using windows 10, node v16. Yes, I am using latest `trunk` commit.

**Comment by dinhtungdu** [comment]
@prashantpaidi I can reproduce your issue on Windows 10. Can you please open a new issue for this problem?

For this issue, do you mind if I take over this issue to avoid delaying the release of the Mini Cart block?

<details>
<summary>Error details in my test.</summary>

```
ERROR in ./assets/css/abstracts/_mixins.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: This file is already being loaded.
      ╷
    1 │ @use "sass:math";@import "_colors"; @import "_variables"; @import "_breakpoints"; @import "_mixins"; $fontSizes: (
      │                                                                                           ^^^^^^^^^
      ╵
      assets\css\abstracts\_mixins.scss 1:91  root stylesheet
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\lib\NormalModule.js:316:20
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:367:11
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:233:18
        at context.callback (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass-loader\dist\index.js:62:7
        at Function.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:99051:16)
        at render_closure1.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:84557:12)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:19793:20
        at _wrapJsFunctionForAsync_closure.$protected (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27919:12)
        at _awaitOnObject_closure0.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27913:25)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:15294:20
        at _wrapJsFunctionForAsync_closure.$protected (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27919:12)
        at _awaitOnObject_closure0.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27913:25)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)

    ERROR in ./assets/css/abstracts/_breakpoints.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: This file is already being loaded.
      ╷
    1 │ @use "sass:math";@import "_colors"; @import "_variables"; @import "_breakpoints"; @import "_mixins"; /* stylelint-disable block-closing-brace-newline-after */
      │                                                                   ^^^^^^^^^^^^^^
      ╵
      assets\css\abstracts\_breakpoints.scss 1:67  root stylesheet
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\lib\NormalModule.js:316:20
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:367:11
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:233:18
        at context.callback (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass-loader\dist\index.js:62:7
        at Function.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:99051:16)
        at render_closure1.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:84557:12)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:19793:20
        at _wrapJsFunctionForAsync_closure.$protected (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27919:12)
        at _awaitOnObject_closure0.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27913:25)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:15294:20
        at _wrapJsFunctionForAsync_closure.$protected (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27919:12)
        at _awaitOnObject_closure0.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27913:25)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)

    ERROR in ./assets/css/abstracts/_colors.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: This file is already being loaded.
      ╷
    1 │ @use "sass:math";@import "_colors"; @import "_variables"; @import "_breakpoints"; @import "_mixins"; @import "node_modules/@wordpress/base-styles/colors";
      │                          ^^^^^^^^^
      ╵
      assets\css\abstracts\_colors.scss 1:26  root stylesheet
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\lib\NormalModule.js:316:20
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:367:11
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:233:18
        at context.callback (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass-loader\dist\index.js:62:7
        at Function.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:99051:16)
        at render_closure1.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:84557:12)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:19793:20
        at _wrapJsFunctionForAsync_closure.$protected (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27919:12)
        at _awaitOnObject_closure0.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27913:25)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:15294:20
        at _wrapJsFunctionForAsync_closure.$protected (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27919:12)
        at _awaitOnObject_closure0.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27913:25)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)

    ERROR in ./assets/css/abstracts/_variables.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: This file is already being loaded.
      ╷
    1 │ @use "sass:math";@import "_colors"; @import "_variables"; @import "_breakpoints"; @import "_mixins"; @import "node_modules/@wordpress/base-styles/variables";
      │                                             ^^^^^^^^^^^^
      ╵
      assets\css\abstracts\_variables.scss 1:45  root stylesheet
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\lib\NormalModule.js:316:20
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:367:11
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:233:18
        at context.callback (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass-loader\dist\index.js:62:7
        at Function.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:99051:16)
        at render_closure1.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:84557:12)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:19793:20
        at _wrapJsFunctionForAsync_closure.$protected (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27919:12)
        at _awaitOnObject_closure0.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27913:25)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)
        at C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:15294:20
        at _wrapJsFunctionForAsync_closure.$protected (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27919:12)
        at _awaitOnObject_closure0.call$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27913:25)
        at _RootZone.runBinary$3$3 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:29579:18)
        at _FutureListener.handleError$1 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28099:21)
        at _Future__propagateToListeners_handleError.call$0 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28406:49)
        at Object._Future__propagateToListeners (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3909:77)
        at _Future._completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:28252:9)
        at _AsyncAwaitCompleter.completeError$2 (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:27900:12)
        at Object._asyncRethrow (C:\Users\Tung\Downloads\woocommerce-gutenberg-products-block\node_modules\sass\sass.dart.js:3712:17)

    ERROR in ./node_modules/wordpress-components/src/combobox-control/style.scss 1:0
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    > .components-combobox-control {
    |   width: 100%;
    | }

    ERROR in ./node_modules/wordpress-components/src/custom-select-control/style.scss 1:0
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    > .components-custom-select-control {
    |   position: relative;
    | }

    ERROR in ./node_modules/wordpress-components/src/snackbar/style.scss 1:0
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    > .components-snackbar {
    |   font-family: $default-font;
    |   font-size: $default-font-size;
```

</details>

**Comment by prashantpaidi** [comment]
@dinhtungdu Okay, I will raise a new issue.

You can take this problem. I can understand.
