### ISSUE TITLE
Cannot build on windows

### ISSUE THREAD

**Issue by Tropicalista** [woocommerce/woocommerce-gutenberg-products-block#7440]
## Describe the bug

Cannot build on Windows

## To reproduce

1. Run `npm run start`

## Expected behavior

Successfull build

### WordPress (please complete the following information):

-   WordPress version: 6.0.1

### Desktop (please complete the following information):

-   OS: Windows

## Additional context

```    ERROR in ./assets/css/abstracts/_mixins.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: This file is already being loaded.
      ╷
    1 │ @use "sass:math";@use "sass:string";@use "sass:color";@use "sass:map";@import "_colors"; @import "_variables"; @import "_breakpoints"; @import "_mixins"; $fontSizes: (
      │
                               ^^^^^^^^^
      ╵
      assets\css\abstracts\_mixins.scss 1:144  root stylesheet
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\webpack\lib\NormalModule.js:316:20
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\loader-runner\lib\LoaderRunner.js:367:11
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\loader-runner\lib\LoaderRunner.js:233:18
        at context.callback (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass-loader\dist\index.js:62:7
        at Function.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:99807:16)
        at render_closure1.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:85345:12)
        at _RootZone.runBinary$3$3 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:29712:18)
        at _FutureListener.handleError$1 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28226:21)
        at _Future__propagateToListeners_handleError.call$0 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28533:49)
        at Object._Future__propagateToListeners (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3936:77)
        at _Future._completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28379:9)
        at _AsyncAwaitCompleter.completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28024:12)
        at Object._asyncRethrow (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3712:17)
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:19922:20
        at _wrapJsFunctionForAsync_closure.$protected (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28043:12)
        at _awaitOnObject_closure0.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28037:25)
        at _RootZone.runBinary$3$3 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:29712:18)
        at _FutureListener.handleError$1 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28226:21)
        at _Future__propagateToListeners_handleError.call$0 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28533:49)
        at Object._Future__propagateToListeners (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3936:77)
        at _Future._completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28379:9)
        at _AsyncAwaitCompleter.completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28024:12)
        at Object._asyncRethrow (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3712:17)
        at D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:15400:20
        at _wrapJsFunctionForAsync_closure.$protected (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3737:15)
        at _wrapJsFunctionForAsync_closure.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28043:12)
        at _awaitOnObject_closure0.call$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28037:25)
        at _RootZone.runBinary$3$3 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:29712:18)
        at _FutureListener.handleError$1 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28226:21)
        at _Future__propagateToListeners_handleError.call$0 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28533:49)
        at Object._Future__propagateToListeners (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3936:77)
        at _Future._completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28379:9)
        at _AsyncAwaitCompleter.completeError$2 (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:28024:12)
        at Object._asyncRethrow (D:\xampp\htdocs\test\wp-content\plugins\woocommerce-blocks\node_modules\sass\sass.dart.js:3712:17)```

**Comment by opr** [comment]
Hi @Tropicalista - thank you for this report. This is something I noticed too when I tried with windows. I have plans to look into this issue over the next few weeks, so please follow https://github.com/woocommerce/woocommerce-blocks/pull/6798 for progress updates!

**Comment by Tropicalista** [comment]
I have checked your fix, but it does not solve my problem

Unfortunately this is out of my competence, so I cannot be helpful. But if you need some testing, let me know.
